"""Adds employee_id column to users table

Revision ID: 01102c069bff
Revises: 26edc91879c5
Create Date: 2019-10-25 17:33:48.283384

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '01102c069bff'
down_revision = '26edc91879c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
