"""Adds 'seniority_list_records' and 'pilot_records' tables

Revision ID: 26edc91879c5
Revises: c63600b80371
Create Date: 2019-10-23 11:25:56.426857

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '26edc91879c5'
down_revision = 'c63600b80371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seniority_list_records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('published_date', sa.DateTime(), nullable=True),
                    sa.Column('added_date', sa.DateTime(), nullable=True),
                    sa.Column('company_name', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pilot_records',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('employee_id', sa.String(length=16), nullable=False),
                    sa.Column('seniority_list_id', sa.Integer(), nullable=True),
                    sa.Column('hire_date', sa.DateTime(), nullable=True),
                    sa.Column('retire_date', sa.DateTime(), nullable=True),
                    sa.Column('literal_seniority_number', sa.Integer(), nullable=True),
                    sa.Column('first_name', sa.String(length=64), nullable=True),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.Column('base', sa.String(length=8), nullable=True),
                    sa.Column('seat', sa.String(length=8), nullable=True),
                    sa.Column('aircraft', sa.String(length=8), nullable=True),
                    sa.ForeignKeyConstraint(['seniority_list_id'], ['seniority_list_records.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_records')
    op.drop_table('seniority_list_records')
    # ### end Alembic commands ###
