"""empty message

Revision ID: 675c195c06eb
Revises: 170616201e02
Create Date: 2020-02-24 12:20:35.023054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "675c195c06eb"
down_revision = "170616201e02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("use_personal_email", sa.Boolean(), nullable=True))
    op.alter_column(
        "users", "personal_email", existing_type=sa.VARCHAR(length=80), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "personal_email", existing_type=sa.VARCHAR(length=80), nullable=False
    )
    op.drop_column("users", "use_personal_email")
    # ### end Alembic commands ###
