"""empty message

Revision ID: e428e8eb4713
Revises: a477a8846c01
Create Date: 2019-10-07 21:44:48.700651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e428e8eb4713'
down_revision = 'a477a8846c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('personal_email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personal_email_confirmed')
    op.drop_column('users', 'company_email_confirmed')
    # ### end Alembic commands ###
